version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    command: redis-server --save 60 1 --loglevel warning
    env_file:
      - .env
    ports:
      - "6379:6379"
    volumes:
      - ./docker_volumes/redis_data:/data
    restart: always
